apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cronjob-config
data:
  entrypoint.sh: |
{{ include "entrypointContent" . | indent 4 }}
  script.py: |
{{ include "scriptContent" . | indent 4 }}
