apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cronjob
spec:
  schedule: "{{ .Values.cronJob.schedule }}"
  concurrencyPolicy: {{ .Values.cronJob.concurrencyPolicy }}
  timezone: {{.Values.cronJob.timezone}}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: script-container
            image: {{ .Values.container.image }}
            command: {{ .Values.container.command }}
            volumeMounts:
            - name: {{ .Values.volumeName }}
              mountPath: /mnt
            env: {{ toYaml .Values.container.env | nindent 12 }}          
          restartPolicy: {{ .Values.cronJob.restartPolicy }}
          volumes:
          - name: script-volume
            configMap:
              name: {{ .Release.Name }}-cronjob-cm
